name: "test-test"
on: push
permissions:
  pull-requests: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Find the PR associated with this push, if there is one.
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - run: echo "${PR}"
      - run: echo "############"
      - run: echo "${{ steps.PR.outputs.pr }}"
