name: "test-test"
on: push
jobs:
  build:
    needs: check-if-releasing-library
    runs-on: ubuntu-latest
    if: ${{ needs.check-if-releasing-library.outputs.result == 'false' }}
    steps:
      - name: Building
        run: echo "Building!"

  include: ./check-if-releasing-library.yml
