name: "test-test"
on: push
jobs:
  check-if-releasing-library:
    uses: ./.github/workflows/check-if-releasing-library.yml
  build:
    needs: check-if-releasing-library
    runs-on: ubuntu-latest
    if: ${{ needs.check-if-releasing-library.outputs.result == 'false' }}
    steps:
      - name: Building
        run: echo "Building!!"
      - run: echo "${{ toJson(needs.check-if-releasing-library.outputs) }}"
