name: "test-test"
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jwalton/gh-find-current-pr@v1
        id: PR
      - run: |
          if [[ "${{ steps.PR.outputs.title }}" == "@storyblok/field-plugin-cli@"* ]]; then
            echo "::set-output name=releasing-library::true"
          else
            echo "::set-output name=releasing-library::false"
          fi
  build:
    needs: check
    runs-on: ubuntu-latest
    # if: ${{ needs.check.outputs.releasing-library == 'false' }}
    steps:
      - name: Building
        run: echo "Building!"
      - run: echo "${{ needs.check.outputs.releasing-library }}"
      - run: echo "${{ toJson(needs.check) }}"
