name: "test-test"
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jwalton/gh-find-current-pr@v1
        id: PR
      - run: |
          echo "title: $${{ steps.PR.outputs.title }}"
          if [[ "${{ steps.PR.outputs.title }}" == "@storyblok/field-plugin-cli@"* ]]; then
            echo "releasing"
            echo "{releasing-library}={true}" >> $GITHUB_OUTPUT
          else
            echo "not releasing"
            echo "{releasing-library}={false}" >> $GITHUB_OUTPUT
          fi
  build:
    needs: check
    runs-on: ubuntu-latest
    if: ${{ needs.check.outputs.releasing-library == 'false' }}
    steps:
      - name: Building
        run: echo "Building!"
