name: "test-test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: PR
        with:
          github-token: ${{ github.token }}
      - run: echo "${PR}"
      - run: echo "############"
      - run: echo "${{ steps.PR }}"
