name: "test-test"
on: push
jobs:
  check:
    uses: ./.github/workflows/check-if-releasing-library.yml

  build:
    needs: check
    runs-on: ubuntu-latest
    # if: ${{ needs.check.outputs.result == 'false' }}
    steps:
      - name: Building
        run: echo "Building!"
      - run: echo "${{ toJson(needs.check.outputs) }}"
