name: "test-test"
on: push
jobs:
  check-if-library-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jwalton/gh-find-current-pr@v1
        id: PR
      - run: |
          if [[ "${{ steps.PR.outputs.title }}" != "@storyblok/field-plugin-cli@"* ]]; then
            echo "Title does not start with @storyblok/field-plugin-cli@"
            exit 1
          fi
  build:
    needs: check-if-library-release
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Building
        run: echo "Building!"
